### ISSUE TITLE
flutter: DartPyException(Importing python module namefinder failed, make sure the namefinder is on your PYTHONPATH  eg. export PYTHONPATH=$PYTHONPATH:/path/to/namefinder)

### ISSUE THREAD

**Issue by rhiotbdq** [TimWhiting/dartpy#3] opened 2021-06-08 15:35 UTC
I have been trying to build a model in python and put that in dart using this library. However, I keep on getting this same error. Can you please walk me through how to set this up such that I can actually run my python function on dart, set up my PYTHONPATH because I am very confused. Thank you so much!

**Comment by TimWhiting** [comment] 2021-06-08 18:54
Sounds like you are having trouble with setting up your PYTHONPATH. Make sure it has your python scripts in the path.
Duplicate of #2

**Closed as completed by TimWhiting** 2021-06-08 18:54 UTC
